version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: usercam-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - usercam

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: usercam-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/src
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
    env_file: 
      - ../.env
    networks:
      - usercam

  frontend:
    image: node:14-alpine
    container_name: usercam-fe
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    networks:
      - usercam

volumes:
  mysql_data:

networks:
  usercam:
    driver: bridge