[package]
name = "all_about_updates"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
diesel = { version = "2.1.0", path = "../../../diesel", features = ["postgres"] }

[lib]
doc = false
