name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v4

    # Setup Rust environment
    - name: Setup Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        components: rustfmt, clippy

    # Check Rust code
    - name: Check Rust code with cargo
      run: |
        cd backend
        cargo check --verbose

    # Run Rust tests
    - name: Run Rust tests with cargo
      run: |
        cd backend
        cargo test --verbose

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    # Install and build React application
    - name: Install and build React App
      run: |
        cd frontend
        npm install
        npm run build

    # Run React tests
    - name: Run React tests
      run: |
        cd frontend
        npm test