name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
    - name: Build and Check Rust
      run: |
        cd backend
        cargo build --verbose
        cargo test --verbose
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install and Build React App
      run: |
        cd frontend
        npm install
        npm run build
    - name: Run Tests
      run: |
        npm test
